services:
  fi-lo-games-api:
    image: 'fi-lo-games-api:latest'
    build:
      context: backend/fi-lo-games
    container_name: fi-lo-games-api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - POSTGRESQL_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - FILO_IMAGES=/app/image-uploads
    ports:
      - "8080:8080"

  db:
    image: 'postgres:14.22-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  fi-lo-games-frontend:
    image: 'fi-lo-games-frontend:latest'
    build:
      context: frontend
    container_name: fi-lo-games-frontend
    ports:
      - "3000:3000"
